
#+TITLE: Castle
#+AUTHOR: Sotla
#+LAST_EDIT: <2024-11-18 Mon 11:55 EST>

* The Gates
This is where we write out general ideas for how we want the game to go.
** What's it gonna look like?
We plan to use our state of the art technology to royally fuck up your
computer monitor. The goal of our visual effects is to feel
"emotionally real" to the experience of the character, with game
design principles like 'readability' and 'unobtrusiveness' thrown
firmly in the garbage where they belong. Visuals will play a major
part in making /you/ feel the pain and discomfort that your character
is going through. Exhaustion blows out your vision, getting shot will
put a white hot bullethole through your screen, a punch to the head
will flashbang your poor troglodyte eyes, and you will see nothing but
darkness when you finally meet your doom. We look forward to hurting
your eyes.
** What's it gonna sound like?
Much like with our visuals, we plan to possess your speakers and use
them against you with the malice we hope you've come to expect from
us.
** What's it gonna play like?
*** Playing pretend
One of the biggest flaws with the last game was the difficulty it took
to maintain an atmosphere of immersive roleplay, especially near the
end of its painfully long life. Fighting this syndrome is a primary
driver behind most major game design decisions. Our goal is to create
a game where roleplaying does not have to be enforced, but is done by
choice because it's encouraged by the mechanics themselves. Common
labor will require teamwork and coordination, catching criminals will
require observation and problem solving on the part of the Sanitar
Squad, and antagonists will be forced to exploit the gaps between
people (through deception, stealth, and blackmail) to achieve their
goals. Gameplay mechanics that don't require/encourage teamwork will
be less efficient.
*** Hurting people
A major target in our roleplay crusade is the combat system. It is too easy to kill someone, but more importantly, it's too easy to /justify/ killing them. Do they have an item you want? Kill them and rob their corpse. Competing for your resources? Kill them and monopolize it for yourself. Someone just pissed you off? Kill them!

We have several ideas to remedy the desire of players to murder each other: The ability of players to respawn will be kept on a tight leash, gathering the strength/gear/buddies to kill someone generally should be a /task/ that requires continuous motivation, permanent injuries will make fighting less than appealing even if you'd be able to win, and murder can make you go mad unless your brain is already fucked up somehow.

Fostering longer-lived characters with more stories to tell in a conflict-ridden place like the Nightmare also means that you need to be able to /lose/ without /dying/. To this end, plentiful blunt weapons will have a much lower capacity for death than rare blades and ever-elusive firearms. No more getting killed by a random pipe-wielding scumbag in the sewer, now him and his buddies will only tie you up and cut your tongue off after they steal your bones.

Overall, we want fights to be won with intimidation, preparation, and teamwork rather than with reflexes and individual strength.
** How many people are gonna play it?
+We don't fucking know, will you?+
** When does the game start up?
Every time you ask this question we add another month to the answer.
* The Keep
This is where we put more formalized plans for specific things we're working on.
** Firearms
** Cooking
